### ISSUE TITLE
There is no way to modify Elo k-factor without changing EloCompetitor class  

### ISSUE THREAD

**Issue by BlankAlmasry** [wdm0006/elote#10]
I feel it would be nicer if it's possible to modify EloCompetitor default k_factor without having to change the class it self
I believe it is completely normally to use different k_factor for each scope, perhaps even in the same scope as fide does

**Comment by wdm0006** [comment]
purpose of doing it that way was so that if you update the class, all new competitors get the newly updated k_factor. Do you have use cases where different competitors in a population would have different k_factors?

**Comment by wdm0006** [comment]
purpose of doing it that way was so that if you update the class, all new competitors get the newly updated k_factor. Do you have use cases where different competitors in a population would have different k_factors?

**Comment by BlankAlmasry** [comment]
I believe fide chess does that for different ratings, I saw few systems as well use different k_factors for amateur matches and pro matches

it feels annoying to me to adjust the package it self for every time k_factor 32 isn't suitable, perhaps a way to modify it without touching the source code would be nice ?

I think the approach you took in glicko rating deviation initial_rd was pretty nice, not all system uses 350 rd very well, perhaps the same apply to k_factor

**Comment by wdm0006** [comment]
Seems reasonable, would you be interested in working on a PR?

**Comment by BlankAlmasry** [comment]
Sure thing
